language: node_js
addons:
  mariadb: '10.1'
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
node_js: '6'
before_script:
- yarn compile
- mysql -u root -e "CREATE USER 'cotizacionesBrou'@'localhost' IDENTIFIED BY 'cotizacionesBrou'"
- mysql -u root -e "GRANT ALL ON cotizacionesBrou.* TO 'cotizacionesBrou'@'localhost'"
- mysql -u root -e "CREATE DATABASE IF NOT EXISTS cotizacionesBrou;"
- yarn migrate-up
- yarn seed
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: V0QpJydA0WpDFbroVN/WG1YuqbT1I9/zmxRI8fngYfDWQPZbUP/kITq9NGAAb83BiYKuGtTYq/1VH05Cy+s8GNRIJQcwFsNb5WKydO8mnvS+rL8Url5bAzIfkgpekbCNr+tTtfn6RjNrwp+6wi5Zmm402QdCafRxiKROTo9N9wwSLcm/J+oTesz0kXu3nl0Bxj8cq4V6hFVSes9GLqJ9RP5LFHYTEwcEE/eLlj7/6NibYe/XmByrUaj7KZ+9EUstzFZbQ59xip2Jh66JOBmLelvLAkmDjuQvzk1Agwq2+Q0W8w6NzKajGbXiBigWdrXrYJVZBOG3pZmQZ1euOShsztyML2NM+cn7RDpce0wPXLJfkGr8q2IGqt7a351ZUdFrkKGrCWrY36AaW4tBv9/kBi8i9LgKMFjEX5ji3JB6vXtjmuqwP2KUJM52CpoZMzry1R8TLhvhz1kXIXhDC/qUrdbBgbkp+d986hAUxkCXNvCu+5+FOoKcPc+clViUVpvjeMLorxfL9LzglmTRZKEm4UxOCSADyI1YqSFzkYAcg9v35iQV3iWnk+SHRBbzlSOvu6e4hZzNBbMifQEVocTBl4hCw1MVh5Bsy9M232GplBqKsIwmkCDh3j5F56EyNTdVtJPCeyH5YXgMh/NKn4s/vy4rX8y7O9RPICYAN2Jj0pk=
  app: cotizaciones-brou
